title: "Robbie Jakob-Whitworth"
email: robbie@rjwhitworth.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  I'm a consultant for AWS Professional Services, helping customers accelerate their business outcomes. I'm also a
  hackathon enthusiast and advocate of cloud computing and technology in general.
baseurl: "/" 
url: "https://robbie.dev/" 
twitter_username: robzwolf
github_username:  robzwolf

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
