[build]
    command = "bundle exec jekyll build"
    publish = "_site/"

[dev]
    command = "bundle exec jekyll serve"


## /tv and /r/tv redirect to https://tv.gh.robbie.dev
[[redirects]]
    from = "/tv/*"
    to = "https://tv.gh.robbie.dev/:splat"

[[redirects]]
    from = "/r/tv/*"
    to = "https://tv.gh.robbie.dev/:splat"


## /mouse and /r/mouse redirect to https://mouse.gh.robbie.dev
[[redirects]]
    from = "/r/mouse"
    to = "https://mouse.gh.robbie.dev/"

[[redirects]]
    from = "/mouse"
    to = "https://mouse.gh.robbie.dev/"


## /pay redirects to https://robbie.cash
[[redirects]]
    from = "/pay/*"
    to = "https://robbie.cash/:splat"
